<?php

namespace App\models;


use App\models\Sell;
use App\models\Article;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($user)
        {
            $user->profile()->create([
                'user_id' => $user->id,
                'about'=> '',
                'hobbies'=>'',
                'firstname' => '',
                'lastname'=> '',
                'adress'=> '',
                'number'=> '',
                'npa'=> '',
                'city'=> '',
                'state'=> '',
                'picture'=> 'image',
            ]);
        });
    }


    public function profile()
    {
        return $this->hasOne(Profile::class);
    }

    public function sell()
    {
        return $this->hasMany(Sell::class);
    }

    public function article()
    {
        return $this->hasMany(Aricle::class);
    }
}
